# Generated by Django 6.0.3 on 2026-05-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0008_rename_falla_acciondia_problema_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetindicador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='targetindicador',
            name='anio',
            field=models.PositiveIntegerField(default=2025, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='targetindicador',
            name='mes',
            field=models.PositiveIntegerField(default=1, verbose_name='Mes'),
        ),
        migrations.AlterUniqueTogether(
            name='targetindicador',
            unique_together={('area', 'indicador', 'anio', 'mes')},
        ),
    ]
