# Generated by Django 6.0.5 on 2026-05-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0009_target_por_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogofalla',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='area',
            name='nombre_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre del área'),
        ),
        migrations.AddField(
            model_name='area',
            name='nombre_es',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre del área'),
        ),
        migrations.AddField(
            model_name='catalogoequipo',
            name='equipo_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='catalogoequipo',
            name='equipo_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='catalogoequipo',
            name='sub_area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sub área'),
        ),
        migrations.AddField(
            model_name='catalogoequipo',
            name='sub_area_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub área'),
        ),
        migrations.AddField(
            model_name='catalogoequipo',
            name='sub_area_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub área'),
        ),
        migrations.AddField(
            model_name='catalogofalla',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='catalogofalla',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='catalogofalla',
            name='tipo_falla',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de falla'),
        ),
        migrations.AddField(
            model_name='catalogofalla',
            name='tipo_falla_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de falla'),
        ),
        migrations.AddField(
            model_name='catalogofalla',
            name='tipo_falla_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de falla'),
        ),
        migrations.AddField(
            model_name='catalogoresponsable',
            name='responsable_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='catalogoresponsable',
            name='responsable_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsable'),
        ),
    ]
