# Generated by Django 6.0.5 on 2026-05-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0010_remove_catalogofalla_descripcion_area_nombre_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paro',
            name='equipo_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='paro',
            name='equipo_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='paro',
            name='falla_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Falla'),
        ),
        migrations.AddField(
            model_name='paro',
            name='falla_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Falla'),
        ),
        migrations.AddField(
            model_name='paro',
            name='responsable_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='paro',
            name='responsable_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsable'),
        ),
    ]
