# Generated by Django 6.0.5 on 2026-06-03 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0011_paro_equipo_en_paro_equipo_es_paro_falla_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('dia', 'Día'), ('noche', 'Noche')], max_length=10, verbose_name='Turno')),
                ('hora', models.PositiveSmallIntegerField(verbose_name='Hora (0-23)')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='Valor (min)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Registro hora x hora',
                'verbose_name_plural': 'Registros hora x hora',
                'ordering': ['area', 'fecha', 'turno', 'hora'],
                'unique_together': {('area', 'fecha', 'turno', 'hora')},
            },
        ),
    ]
