# Generated by Django 6.0.5 on 2026-06-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0012_registrohorahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohorahora',
            name='valor',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad producida'),
        ),
        migrations.CreateModel(
            name='TargetHoraHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('target_skid', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Target skid por hora')),
                ('target_eficiencia', models.FloatField(blank=True, null=True, verbose_name='Target eficiencia %')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Target hora x hora',
                'verbose_name_plural': 'Targets hora x hora',
                'unique_together': {('area', 'anio', 'mes')},
            },
        ),
    ]
