# Generated by Django 6.0.5 on 2026-06-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0013_alter_registrohorahora_valor_targethorahora'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAnualHoraHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('target_eficiencia', models.FloatField(blank=True, null=True, verbose_name='Target eficiencia anual %')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Target anual hora x hora',
                'verbose_name_plural': 'Targets anuales hora x hora',
                'unique_together': {('area', 'anio')},
            },
        ),
    ]
