# Generated by Django 6.0.5 on 2026-06-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0014_targetanualhorahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='paro',
            name='atendio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Atendió la falla'),
        ),
    ]
