# Generated by Django 6.0.6 on 2026-06-10 02:06

import django.db.models.deletion
import paros_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0015_paro_atendio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paro',
            name='estatus',
            field=models.CharField(choices=[('rojo', 'Rechazado'), ('amarillo', 'Pendiente'), ('verde', 'Aceptado')], default='rojo', max_length=10, verbose_name='Estatus'),
        ),
        migrations.CreateModel(
            name='ImagenParo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=paros_app.models.imagen_paro_upload_path, verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('paro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='paros_app.paro', verbose_name='Paro')),
            ],
            options={
                'verbose_name': 'Imagen de paro',
                'verbose_name_plural': 'Imágenes de paro',
                'ordering': ['subida_en'],
            },
        ),
    ]
