# Generated by Django 6.0.6 on 2026-08-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0016_alter_paro_estatus_imagenparo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_molde', models.CharField(max_length=30, verbose_name='Número de molde')),
                ('nombre_molde', models.CharField(max_length=300, verbose_name='Nombre de molde')),
            ],
            options={
                'verbose_name': 'Molde de catálogo',
                'verbose_name_plural': 'Catálogo de moldes',
                'ordering': ['area', 'numero_molde'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMoldes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Configuración de moldes',
                'verbose_name_plural': 'Configuración de moldes',
            },
        ),
        migrations.AlterField(
            model_name='paro',
            name='estatus',
            field=models.CharField(choices=[('rojo', 'Rechazado'), ('amarillo', 'Pendiente'), ('verde', 'Aceptado')], db_index=True, default='rojo', max_length=10, verbose_name='Estatus'),
        ),
        migrations.AddIndex(
            model_name='paro',
            index=models.Index(fields=['area', 'fecha'], name='paro_area_fecha_idx'),
        ),
        migrations.AddField(
            model_name='catalogomolde',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_moldes', to='paros_app.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='configuracionmoldes',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paros_app.area', verbose_name='Área de moldes'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogomolde',
            unique_together={('area', 'numero_molde')},
        ),
    ]
