# Generated by Django 6.0.6 on 2026-08-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0017_catalogomolde_configuracionmoldes_alter_paro_estatus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroproduccion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='nombre_molde',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nombre de molde'),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='numero_molde',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de molde'),
        ),
    ]
