# Generated by Django 6.0.6 on 2026-08-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0018_alter_registroproduccion_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHoraHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paros_app.area', verbose_name='Área de hora x hora')),
            ],
            options={
                'verbose_name': 'Configuración de hora x hora',
                'verbose_name_plural': 'Configuración de hora x hora',
            },
        ),
    ]
