# Generated by Django 6.0.6 on 2026-08-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0019_configuracionhorahora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAgv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paros_app.area', verbose_name='Área de bitácora de AGVs')),
            ],
            options={
                'verbose_name': 'Configuración de bitácora de AGVs',
                'verbose_name_plural': 'Configuración de bitácora de AGVs',
            },
        ),
        migrations.CreateModel(
            name='RegistroAgv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_interna', models.CharField(choices=[('inyeccion', 'Inyección'), ('pintura', 'Pintura')], max_length=10, verbose_name='Área interna')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('dia', 'Día'), ('noche', 'Noche')], max_length=10, verbose_name='Turno')),
                ('cantidad', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de AGVs')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Registro de AGVs',
                'verbose_name_plural': 'Registros de AGVs',
                'ordering': ['area', 'fecha', 'turno', 'area_interna'],
                'unique_together': {('area', 'area_interna', 'fecha', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='TargetAgv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_interna', models.CharField(choices=[('inyeccion', 'Inyección'), ('pintura', 'Pintura')], max_length=10, verbose_name='Área interna')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('target_cantidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Target de AGVs')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Target de AGVs',
                'verbose_name_plural': 'Targets de AGVs',
                'unique_together': {('area', 'area_interna', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='TargetAnualAgv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_interna', models.CharField(choices=[('inyeccion', 'Inyección'), ('pintura', 'Pintura')], max_length=10, verbose_name='Área interna')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('target_cantidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Target anual de AGVs')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Target anual de AGVs',
                'verbose_name_plural': 'Targets anuales de AGVs',
                'unique_together': {('area', 'area_interna', 'anio')},
            },
        ),
    ]
