# Generated by Django 6.0.6 on 2026-08-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0020_configuracionagv_registroagv_targetagv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetAnualAgv',
        ),
    ]
