# Generated by Django 6.0.6 on 2026-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0021_delete_targetanualagv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciondia',
            name='cont_estatus',
            field=models.CharField(choices=[('p', 'Pendiente'), ('e', 'En proceso'), ('c', 'Cerrada'), ('n', 'No aplica')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='acciondia',
            name='corr_estatus',
            field=models.CharField(choices=[('p', 'Pendiente'), ('e', 'En proceso'), ('c', 'Cerrada'), ('n', 'No aplica')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='acciondia',
            name='prev_estatus',
            field=models.CharField(choices=[('p', 'Pendiente'), ('e', 'En proceso'), ('c', 'Cerrada'), ('n', 'No aplica')], default='p', max_length=1),
        ),
    ]
