# Generated by Django 6.0.6 on 2026-08-26 02:25

from django.db import migrations, models

def backfill_equipo_es_en(apps, schema_editor):
    """Los registros existentes solo tenían `equipo` en un idioma (el que
    estaba activo al crearlos). Se busca el equipo en el catálogo bilingüe
    para llenar equipo_es/equipo_en de forma consistente; si no hay match,
    se usa el mismo texto para ambos idiomas (mismo criterio que paros.py)."""
    RegistroProduccion = apps.get_model('paros_app', 'RegistroProduccion')
    CatalogoEquipo = apps.get_model('paros_app', 'CatalogoEquipo')

    for reg in RegistroProduccion.objects.exclude(equipo=''):
        texto = (reg.equipo or '').strip()
        if not texto:
            continue
        catalogo = CatalogoEquipo.objects.filter(area=reg.area).filter(
            models.Q(equipo_es=texto) | models.Q(equipo_en=texto)
        ).first()
        if catalogo:
            reg.equipo_es = catalogo.equipo_es or catalogo.equipo_en or texto
            reg.equipo_en = catalogo.equipo_en or catalogo.equipo_es or texto
        else:
            reg.equipo_es = texto
            reg.equipo_en = texto
        reg.save(update_fields=['equipo_es', 'equipo_en'])


def noop_reverse(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0022_alter_acciondia_cont_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproduccion',
            name='equipo_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='equipo_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.RunPython(backfill_equipo_es_en, noop_reverse),
    ]
