# Generated by Django 6.0.6 on 2026-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0023_registroproduccion_equipo_bilingue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciondia',
            name='cont_accion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='acciondia',
            name='corr_accion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='acciondia',
            name='prev_accion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
