# Generated by Django 6.0.6 on 2026-06-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mto_app', '0008_imagenseguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de refacción',
                'verbose_name_plural': 'Categorías de refacciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.CharField(max_length=50, verbose_name='No. Item')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('unidad', models.CharField(choices=[('pza', 'Pieza'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('mt', 'Metro'), ('caja', 'Caja'), ('par', 'Par'), ('docena', 'Docena')], default='pza', max_length=10, verbose_name='Unidad')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en almacén')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mto_app.area', verbose_name='Área')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_app.categoriarefaccion', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Refacción',
                'verbose_name_plural': 'Refacciones',
                'ordering': ['area', 'no_item'],
                'unique_together': {('area', 'no_item')},
            },
        ),
    ]
