# Generated by Django 6.0.6 on 2026-06-17 22:08

import django.db.models.deletion
import inventario_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=inventario_app.models.imagen_refaccion_upload_path, verbose_name='Imagen')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario_app.refaccion', verbose_name='Refacción')),
            ],
            options={
                'verbose_name': 'Imagen de refacción',
                'verbose_name_plural': 'Imágenes de refacción',
                'ordering': ['subida_en'],
            },
        ),
    ]
