# Generated by Django 6.0.6 on 2026-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_imagenrefaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='no_item',
            field=models.CharField(max_length=10, verbose_name='No. Item'),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=4, verbose_name='Ubicación en almacén'),
        ),
    ]
