# Generated by Django 6.0.6 on 2026-06-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_alter_refaccion_no_item_alter_refaccion_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad pedida')),
                ('numero_pr', models.CharField(max_length=50, verbose_name='No. PR')),
                ('fecha_pr', models.DateField(blank=True, null=True, verbose_name='Fecha PR')),
                ('numero_po', models.CharField(blank=True, max_length=50, verbose_name='No. PO')),
                ('fecha_po', models.DateField(blank=True, null=True, verbose_name='Fecha PO')),
                ('numero_sr', models.CharField(blank=True, max_length=50, verbose_name='No. SR')),
                ('fecha_sr', models.DateField(blank=True, null=True, verbose_name='Fecha SR')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='inventario_app.refaccion', verbose_name='Refacción')),
            ],
            options={
                'verbose_name': 'Seguimiento de refacción',
                'verbose_name_plural': 'Seguimientos de refacciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
