# Generated by Django 6.0.6 on 2026-06-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_seguimientorefaccion'),
        ('mto_app', '0009_accesomto_editar_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.CharField(max_length=10, verbose_name='No. Item')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('motivo_servicio', models.CharField(max_length=200, verbose_name='Motivo del servicio')),
                ('numero_pr', models.CharField(max_length=50, verbose_name='No. PR')),
                ('fecha_pr', models.DateField(blank=True, null=True, verbose_name='Fecha PR')),
                ('numero_po', models.CharField(blank=True, max_length=50, verbose_name='No. PO')),
                ('fecha_po', models.DateField(blank=True, null=True, verbose_name='Fecha PO')),
                ('numero_sr', models.CharField(blank=True, max_length=50, verbose_name='No. SR')),
                ('fecha_sr', models.DateField(blank=True, null=True, verbose_name='Fecha SR')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mto_app.area', verbose_name='Área')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_app.tiposervicio', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de servicio',
                'verbose_name_plural': 'Seguimientos de servicios',
                'ordering': ['-creado_en'],
            },
        ),
    ]
