# Generated by Django 6.0.6 on 2026-06-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0005_tiposervicio_seguimientoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock máximo'),
        ),
    ]
