# Generated by Django 6.0.6 on 2026-08-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0006_refaccion_stock_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='criticidad',
            field=models.CharField(choices=[('critico', 'Crítico'), ('no_critico', 'No crítico')], default='no_critico', max_length=12, verbose_name='Criticidad'),
        ),
    ]
