# Generated by Django 6.0.6 on 2026-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0007_refaccion_criticidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriarefaccion',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='categoriarefaccion',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Categoría'),
        ),
    ]
