# Generated by Django 6.0.4 on 2026-04-25 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Área')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de equipo')),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipos de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('equipo', models.CharField(max_length=200, verbose_name='Equipo / Máquina')),
                ('rutina', models.CharField(max_length=200, verbose_name='Rutina')),
                ('plan_trabajo', models.CharField(help_text='Número o clave del documento de referencia', max_length=100, verbose_name='N° Plan de trabajo')),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duración estimada (horas)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mto_app.area', verbose_name='Área')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mto_app.tipoequipo', verbose_name='Tipo de equipo')),
            ],
            options={
                'verbose_name': 'Plan de mantenimiento',
                'verbose_name_plural': 'Planes de mantenimiento',
                'ordering': ['area', 'codigo'],
            },
        ),
    ]
