# Generated by Django 6.0.5 on 2026-06-02 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='tipo_equipo',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='duracion_horas',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='equipo',
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='actividad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='anio_inicio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anio de inicio'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duracion en minutos'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='estatus',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada')], default='Abierta', max_length=20, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='locacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Locacion'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='semana_inicio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana de inicio'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='tipo_mto',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Predictivo', 'Predictivo')], default='Preventivo', max_length=20, verbose_name='Tipo de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='planmantenimiento',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mto_app.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='planmantenimiento',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='planmantenimiento',
            name='plan_trabajo',
            field=models.CharField(max_length=100, verbose_name='Plan de trabajo'),
        ),
        migrations.CreateModel(
            name='AccesoMto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Acceso a Gestión de Mantenimiento')),
                ('areas', models.ManyToManyField(blank=True, to='mto_app.area', verbose_name='Áreas permitidas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_mto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso MTO',
            },
        ),
        migrations.CreateModel(
            name='HistorialRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('importar', 'Importar'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Acción')),
                ('plan_trabajo', models.CharField(blank=True, max_length=100, verbose_name='N° Plan de trabajo')),
                ('codigo_plan', models.CharField(blank=True, max_length=50, verbose_name='Código del plan')),
                ('nombre_plan', models.CharField(blank=True, max_length=255, verbose_name='Nombre del plan')),
                ('pasos_afectados', models.PositiveIntegerField(default=0, verbose_name='Pasos afectados')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mto_app.area', verbose_name='Área')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de rutina',
                'verbose_name_plural': 'Historial de rutinas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_trabajo', models.CharField(db_index=True, max_length=100, verbose_name='N° Plan de trabajo')),
                ('nombre_plan', models.CharField(blank=True, max_length=255, verbose_name='Nombre del plan')),
                ('codigo_plan', models.CharField(blank=True, max_length=50, verbose_name='Codigo del plan')),
                ('secuencia', models.PositiveIntegerField(verbose_name='Seq #')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mto_app.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Paso de rutina',
                'verbose_name_plural': 'Pasos de rutina',
                'ordering': ['plan_trabajo', 'secuencia'],
                'unique_together': {('area', 'plan_trabajo', 'secuencia')},
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nomina', models.CharField(max_length=20, verbose_name='Numero de nomina')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('posicion', models.CharField(blank=True, max_length=100, verbose_name='Posicion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Ultima edicion')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mto_app.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['area', 'apellidos', 'nombre'],
                'unique_together': {('area', 'numero_nomina')},
            },
        ),
        migrations.CreateModel(
            name='RegistroEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_num', models.PositiveIntegerField(verbose_name='Numero de semana')),
                ('anio', models.PositiveIntegerField(verbose_name='Anio')),
                ('semana_inicio', models.DateField(verbose_name='Lunes de la semana')),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('reagendada', 'Reagendada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_ejecucion', models.DateField(blank=True, null=True, verbose_name='Fecha de ejecucion')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='mto_app.planmantenimiento', verbose_name='Plan')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mto_app.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Registro de ejecucion',
                'verbose_name_plural': 'Registros de ejecucion',
                'ordering': ['-anio', '-semana_num'],
                'unique_together': {('plan', 'semana_inicio')},
            },
        ),
        migrations.DeleteModel(
            name='TipoEquipo',
        ),
    ]
