# Generated by Django 6.0.5 on 2026-06-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0002_remove_planmantenimiento_tipo_equipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correctiva', 'Correctiva')], default='correctiva', max_length=20, verbose_name='Tipo')),
                ('problema', models.TextField(verbose_name='Problema encontrado')),
                ('accion', models.TextField(blank=True, default='', verbose_name='Acción realizada')),
                ('responsable', models.CharField(blank=True, default='', max_length=100, verbose_name='Responsable')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha compromiso')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estatus')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='mto_app.historialrutina', verbose_name='Ejecución OT')),
            ],
            options={
                'verbose_name': 'Seguimiento de OT',
                'verbose_name_plural': 'Seguimientos de OT',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
