# Generated by Django 6.0.5 on 2026-06-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0003_seguimientoot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientoot',
            name='historial',
        ),
        migrations.AddField(
            model_name='seguimientoot',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='mto_app.registroejecucion', verbose_name='Registro de ejecución'),
            preserve_default=False,
        ),
    ]
