# Generated by Django 6.0.5 on 2026-06-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0004_remove_seguimientoot_historial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField(unique=True, verbose_name='Consecutivo')),
                ('tipo', models.CharField(choices=[('correctiva', 'Correctiva')], default='correctiva', max_length=20)),
                ('problema', models.TextField(verbose_name='Problema encontrado')),
                ('accion', models.TextField(blank=True, default='', verbose_name='Acción realizada')),
                ('responsable', models.CharField(blank=True, default='', max_length=100, verbose_name='Responsable')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha compromiso')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_app.area', verbose_name='Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento manual',
                'verbose_name_plural': 'Seguimientos manuales',
                'ordering': ['-consecutivo'],
            },
        ),
    ]
