# Generated by Django 6.0.5 on 2026-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0005_seguimientomanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientomanual',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
        migrations.AddField(
            model_name='seguimientoot',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
    ]
