# Generated by Django 6.0.5 on 2026-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0006_seguimientomanual_validado_seguimientoot_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesomto',
            name='editar_plan_mantenimiento',
            field=models.BooleanField(default=False, verbose_name='Editar plan de mantenimiento'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='editar_responsables',
            field=models.BooleanField(default=False, verbose_name='Editar responsables'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='editar_rutinas',
            field=models.BooleanField(default=False, verbose_name='Editar rutinas'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='editar_seguimiento',
            field=models.BooleanField(default=False, verbose_name='Editar seguimiento'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_plan_mantenimiento',
            field=models.BooleanField(default=False, verbose_name='Ver plan de mantenimiento'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_responsables',
            field=models.BooleanField(default=False, verbose_name='Ver responsables'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_rutinas',
            field=models.BooleanField(default=False, verbose_name='Ver rutinas'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_seguimiento',
            field=models.BooleanField(default=False, verbose_name='Ver seguimiento'),
        ),
    ]
