# Generated by Django 6.0.6 on 2026-06-17 15:42

import django.db.models.deletion
import mto_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0007_accesomto_editar_plan_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=mto_app.models.imagen_seguimiento_upload_path, verbose_name='Imagen')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('seguimiento_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mto_app.seguimientomanual')),
                ('seguimiento_ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mto_app.seguimientoot')),
            ],
            options={
                'verbose_name': 'Imagen de seguimiento',
                'verbose_name_plural': 'Imágenes de seguimiento',
                'ordering': ['subida_en'],
            },
        ),
    ]
