# Generated by Django 6.0.6 on 2026-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0008_imagenseguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesomto',
            name='editar_inventario',
            field=models.BooleanField(default=False, verbose_name='Editar inventario'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='editar_seguimiento_refaccion',
            field=models.BooleanField(default=False, verbose_name='Editar seguimiento de refacciones'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_inventario',
            field=models.BooleanField(default=False, verbose_name='Eliminar inventario'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_plan_mantenimiento',
            field=models.BooleanField(default=False, verbose_name='Eliminar plan de mantenimiento'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_responsables',
            field=models.BooleanField(default=False, verbose_name='Eliminar responsables'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_rutinas',
            field=models.BooleanField(default=False, verbose_name='Eliminar rutinas'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_seguimiento',
            field=models.BooleanField(default=False, verbose_name='Eliminar seguimiento'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_seguimiento_refaccion',
            field=models.BooleanField(default=False, verbose_name='Eliminar seguimiento de refacciones'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_backlog',
            field=models.BooleanField(default=False, verbose_name='Ver backlog'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_dashboard',
            field=models.BooleanField(default=False, verbose_name='Ver dashboard'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_inventario',
            field=models.BooleanField(default=False, verbose_name='Ver inventario'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_seguimiento_refaccion',
            field=models.BooleanField(default=False, verbose_name='Ver seguimiento de refacciones'),
        ),
    ]
