# Generated by Django 6.0.6 on 2026-06-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0009_accesomto_editar_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesomto',
            name='editar_seguimiento_servicio',
            field=models.BooleanField(default=False, verbose_name='Editar seguimiento de servicios'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_seguimiento_servicio',
            field=models.BooleanField(default=False, verbose_name='Eliminar seguimiento de servicios'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_seguimiento_servicio',
            field=models.BooleanField(default=False, verbose_name='Ver seguimiento de servicios'),
        ),
    ]
