# Generated by Django 6.0.6 on 2026-07-10 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0010_accesomto_editar_seguimiento_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesomto',
            name='editar_bitacora',
            field=models.BooleanField(default=False, verbose_name='Editar bitácora'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_bitacora',
            field=models.BooleanField(default=False, verbose_name='Eliminar bitácora'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_bitacora',
            field=models.BooleanField(default=False, verbose_name='Ver bitácora'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('equipo', models.CharField(blank=True, max_length=100, verbose_name='Equipo')),
                ('actividad_realizada', models.CharField(max_length=300, verbose_name='Actividad realizada')),
                ('pendiente', models.CharField(blank=True, max_length=200, verbose_name='Pendiente')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mto_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
