# Generated by Django 6.0.6 on 2026-08-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0011_accesomto_editar_bitacora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmantenimiento',
            name='frecuencia',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, verbose_name='Frecuencia'),
        ),
    ]
