# Generated by Django 6.0.6 on 2026-08-06 04:43

import django.db.models.deletion
import mto_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0012_alter_planmantenimiento_frecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=mto_app.models.imagen_bitacora_upload_path, verbose_name='Imagen')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mto_app.bitacora', verbose_name='Bitácora')),
            ],
            options={
                'verbose_name': 'Imagen de bitácora',
                'verbose_name_plural': 'Imágenes de bitácora',
                'ordering': ['subida_en'],
            },
        ),
    ]
