# Generated by Django 6.0.6 on 2026-08-13 01:41

import django.core.validators
import django.db.models.deletion
import mto_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0013_imagenbitacora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesomto',
            name='editar_documentacion',
            field=models.BooleanField(default=False, verbose_name='Editar documentación'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='eliminar_documentacion',
            field=models.BooleanField(default=False, verbose_name='Eliminar documentación'),
        ),
        migrations.AddField(
            model_name='accesomto',
            name='ver_documentacion',
            field=models.BooleanField(default=False, verbose_name='Ver documentación'),
        ),
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Categoría de documento',
                'verbose_name_plural': 'Categorías de documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to=mto_app.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'docx', 'doc', 'pptx', 'ppt']), mto_app.models.validar_tamano_documento], verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido en')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mto_app.categoriadocumento', verbose_name='Categoría')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
