# Generated by Django 6.0.6 on 2026-08-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0014_accesomto_editar_documentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadocumento',
            name='codigo',
            field=models.CharField(default='Test 1', max_length=30, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
