# Generated by Django 6.0.6 on 2026-08-16 18:04

import django.core.validators
import mto_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0015_categoriadocumento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=mto_app.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'docx', 'doc', 'pptx', 'ppt', 'jpg', 'jpeg', 'png', 'webp']), mto_app.models.validar_tamano_documento], verbose_name='Archivo'),
        ),
    ]
