# Generated by Django 6.1.1 on 2026-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0017_subcarpetadocumento_documento_subcarpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcarpetadocumento',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código'),
        ),
    ]
