# Generated by Django 6.1.1 on 2026-09-20 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0018_subcarpetadocumento_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='mto_app.carpeta', verbose_name='Carpeta padre')),
            ],
            options={
                'verbose_name': 'Carpeta de documentos',
                'verbose_name_plural': 'Carpetas de documentos',
                'ordering': ['nombre'],
                'unique_together': {('parent', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mto_app.carpeta', verbose_name='Carpeta'),
        ),
    ]
