# Generated by Django 6.1.1 on 2026-09-20 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto_app', '0020_migrar_categorias_y_subcarpetas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcarpetadocumento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcarpetadocumento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcarpetadocumento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='subcarpeta',
        ),
        migrations.AlterField(
            model_name='documento',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mto_app.carpeta', verbose_name='Carpeta'),
        ),
        migrations.DeleteModel(
            name='CategoriaDocumento',
        ),
        migrations.DeleteModel(
            name='SubcarpetaDocumento',
        ),
    ]
