# Generated by Django 6.0.5 on 2026-06-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_perfilusuario_areas_produccion'),
        ('paros_app', '0014_targetanualhorahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='areas_hora_hora',
            field=models.ManyToManyField(blank=True, related_name='usuarios_hora_hora', to='paros_app.area', verbose_name='Áreas de hora x hora'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ver_hora_hora',
            field=models.BooleanField(default=False, verbose_name='Ver hora x hora'),
        ),
    ]
