# Generated by Django 6.0.5 on 2026-06-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_perfilusuario_areas_hora_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ver_indicadores',
            field=models.BooleanField(default=False, verbose_name='Ver indicadores de producción'),
        ),
    ]
