# Generated by Django 6.0.5 on 2026-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_perfilusuario_ver_indicadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='agregar_catalogo_equipo',
            field=models.BooleanField(default=False, verbose_name='Agregar equipo al catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='agregar_catalogo_falla',
            field=models.BooleanField(default=False, verbose_name='Agregar falla al catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='agregar_catalogo_resp',
            field=models.BooleanField(default=False, verbose_name='Agregar responsable al catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='editar_catalogo_equipo',
            field=models.BooleanField(default=False, verbose_name='Editar equipo del catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='editar_catalogo_falla',
            field=models.BooleanField(default=False, verbose_name='Editar falla del catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='editar_catalogo_resp',
            field=models.BooleanField(default=False, verbose_name='Editar responsable del catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='eliminar_catalogo_equipo',
            field=models.BooleanField(default=False, verbose_name='Eliminar equipo del catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='eliminar_catalogo_falla',
            field=models.BooleanField(default=False, verbose_name='Eliminar falla del catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='eliminar_catalogo_resp',
            field=models.BooleanField(default=False, verbose_name='Eliminar responsable del catálogo'),
        ),
    ]
