# Generated by Django 6.0.6 on 2026-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_perfilusuario_agregar_catalogo_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='agregar_catalogo_molde',
            field=models.BooleanField(default=False, verbose_name='Agregar molde al catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='editar_catalogo_molde',
            field=models.BooleanField(default=False, verbose_name='Editar molde del catálogo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='eliminar_catalogo_molde',
            field=models.BooleanField(default=False, verbose_name='Eliminar molde del catálogo'),
        ),
    ]
