# Generated by Django 6.0.6 on 2026-08-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_perfilusuario_agregar_catalogo_molde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='editar_bitacora_agv',
            field=models.BooleanField(default=False, verbose_name='Editar bitácora de AGVs'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ver_bitacora_agv',
            field=models.BooleanField(default=False, verbose_name='Ver bitácora de AGVs'),
        ),
    ]
